# Generated by Django 3.2 on 2023-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_book', '0002_auto_20230427_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='desc_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='desc_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
